using Finstance.dbContext.Models;

namespace Finstance.dbContext;

public static class ExpenseLocationSeedData
{
    public static readonly List<ExpenseLocationModel> Locations = new()
    {
        new ExpenseLocationModel { Id = 1, Name = "MİGROS", NormalizedName = "MIGROS", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 2, Name = "CARREFOUR", NormalizedName = "CARREFOUR", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 3, Name = "CARREFOURSA", NormalizedName = "CARREFOURSA", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 4, Name = "BİM", NormalizedName = "BIM", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 5, Name = "A101", NormalizedName = "A101", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 6, Name = "ŞOK MARKET", NormalizedName = "SOK MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 7, Name = "METRO GROSMARKET", NormalizedName = "METRO GROSMARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 8, Name = "FİLE MARKET", NormalizedName = "FILE MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 9, Name = "TARIM KREDİ", NormalizedName = "TARIM KREDI", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 10, Name = "HAKMAR", NormalizedName = "HAKMAR", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 11, Name = "BİZİM TOPTAN", NormalizedName = "BIZIM TOPTAN", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 12, Name = "MACROCENTER", NormalizedName = "MACROCENTER", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 13, Name = "ONUR MARKET", NormalizedName = "ONUR MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 14, Name = "ÇAĞRI MARKET", NormalizedName = "CAGRI MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 15, Name = "HAPPY CENTER", NormalizedName = "HAPPY CENTER", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 16, Name = "KİM MARKET", NormalizedName = "KIM MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 17, Name = "BİÇEN", NormalizedName = "BICEN", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 18, Name = "PEHLİVANOĞLU", NormalizedName = "PEHLIVANOGLU", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 19, Name = "MOPAŞ", NormalizedName = "MOPAS", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 20, Name = "YUNUS MARKET", NormalizedName = "YUNUS MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 21, Name = "SARIYER MARKET", NormalizedName = "SARIYER MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 22, Name = "SHOW MARKET", NormalizedName = "SHOW MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 23, Name = "ALTUNBİLEKLER", NormalizedName = "ALTUNBILEKLER", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 24, Name = "ESENLİK", NormalizedName = "ESENLIK", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 25, Name = "GROSERİ", NormalizedName = "GROSERI", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 26, Name = "BAŞDAŞ", NormalizedName = "BASDAS", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 27, Name = "ÖZHAN", NormalizedName = "OZHAN", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 28, Name = "SEYHANLAR", NormalizedName = "SEYHANLAR", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 29, Name = "GETİR", NormalizedName = "GETIR", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 30, Name = "İSTEGELSİN", NormalizedName = "ISTEGELSIN", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 31, Name = "BANABİ", NormalizedName = "BANABI", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 32, Name = "TRENDYOL HIZLI MARKET", NormalizedName = "TRENDYOL HIZLI MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 33, Name = "YEMEKSEPETİ MARKET", NormalizedName = "YEMEKSEPETI MARKET", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 34, Name = "GRATİS", NormalizedName = "GRATIS", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 35, Name = "WATSONS", NormalizedName = "WATSONS", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 36, Name = "ROSSMANN", NormalizedName = "ROSSMANN", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 37, Name = "COSMETICA", NormalizedName = "COSMETICA", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 38, Name = "SEPHORA", NormalizedName = "SEPHORA", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 39, Name = "EVE KOZMETİK", NormalizedName = "EVE KOZMETIK", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 40, Name = "FLORMAR", NormalizedName = "FLORMAR", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 41, Name = "KIKO", NormalizedName = "KIKO", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 42, Name = "GOLDEN ROSE", NormalizedName = "GOLDEN ROSE", Category = ExpenseCategory.Market },
        new ExpenseLocationModel { Id = 79, Name = "YEMEKSEPETİ", NormalizedName = "YEMEKSEPETI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 80, Name = "GETİR YEMEK", NormalizedName = "GETIR YEMEK", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 81, Name = "TRENDYOL YEMEK", NormalizedName = "TRENDYOL YEMEK", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 82, Name = "FUUDY", NormalizedName = "FUUDY", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 83, Name = "TIKLA GELSİN", NormalizedName = "TIKLA GELSIN", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 84, Name = "BURGER KING", NormalizedName = "BURGER KING", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 85, Name = "MCDONALD'S", NormalizedName = "MCDONALD'S", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 86, Name = "KFC", NormalizedName = "KFC", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 87, Name = "POPEYES", NormalizedName = "POPEYES", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 88, Name = "SUBWAY", NormalizedName = "SUBWAY", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 89, Name = "DOMİNOS", NormalizedName = "DOMINOS", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 90, Name = "PIZZA HUT", NormalizedName = "PIZZA HUT", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 91, Name = "LITTLE CAESARS", NormalizedName = "LITTLE CAESARS", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 92, Name = "PASAPORT PIZZA", NormalizedName = "PASAPORT PIZZA", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 93, Name = "TERRA PIZZA", NormalizedName = "TERRA PIZZA", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 94, Name = "PAPA JOHNS", NormalizedName = "PAPA JOHNS", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 95, Name = "ARBY'S", NormalizedName = "ARBY'S", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 96, Name = "CARL'S JR", NormalizedName = "CARL'S JR", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 97, Name = "SHAKE SHACK", NormalizedName = "SHAKE SHACK", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 98, Name = "HD İSKENDER", NormalizedName = "HD ISKENDER", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 99, Name = "PİDEM", NormalizedName = "PIDEM", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 100, Name = "TAVUK DÜNYASI", NormalizedName = "TAVUK DUNYASI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 101, Name = "KÖFTECİ YUSUF", NormalizedName = "KOFTECI YUSUF", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 102, Name = "BAYDÖNER", NormalizedName = "BAYDONER", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 103, Name = "USTA DÖNERCİ", NormalizedName = "USTA DONERCI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 104, Name = "BEREKET DÖNER", NormalizedName = "BEREKET DONER", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 105, Name = "SBARRO", NormalizedName = "SBARRO", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 106, Name = "DÜRÜMLE", NormalizedName = "DURUMLE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 107, Name = "KOMAGENE", NormalizedName = "KOMAGENE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 108, Name = "OSES", NormalizedName = "OSES", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 109, Name = "O SES CIGKOFTE", NormalizedName = "O SES CIGKOFTE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 110, Name = "BATTALBEY", NormalizedName = "BATTALBEY", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 111, Name = "ÇİĞKÖFTEM", NormalizedName = "CIGKOFTEM", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 112, Name = "STARBUCKS", NormalizedName = "STARBUCKS", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 113, Name = "KAHVE DÜNYASI", NormalizedName = "KAHVE DUNYASI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 114, Name = "ESPRESSOLAB", NormalizedName = "ESPRESSOLAB", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 115, Name = "TCHIBO", NormalizedName = "TCHIBO", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 116, Name = "GLORIA JEAN", NormalizedName = "GLORIA JEAN", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 117, Name = "CARIBOU", NormalizedName = "CARIBOU", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 118, Name = "CAFE NERO", NormalizedName = "CAFE NERO", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 119, Name = "CAFFE NERO", NormalizedName = "CAFFE NERO", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 120, Name = "MOC COFFEE", NormalizedName = "MOC COFFEE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 121, Name = "FEDERAL COFFEE", NormalizedName = "FEDERAL COFFEE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 122, Name = "COFFEESHOP", NormalizedName = "COFFEESHOP", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 123, Name = "SİMİT SARAYI", NormalizedName = "SIMIT SARAYI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 124, Name = "SİMİT DÜŞLERİ", NormalizedName = "SIMIT DUSLERI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 125, Name = "MADO", NormalizedName = "MADO", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 126, Name = "KAFEPI", NormalizedName = "KAFEPI", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 127, Name = "BİG CHEFS", NormalizedName = "BIG CHEFS", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 128, Name = "MIDPOINT", NormalizedName = "MIDPOINT", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 129, Name = "COOKSHOP", NormalizedName = "COOKSHOP", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 130, Name = "THE HOUSE CAFE", NormalizedName = "THE HOUSE CAFE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 131, Name = "HAPPY MOON'S", NormalizedName = "HAPPY MOON'S", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 132, Name = "HUQQA", NormalizedName = "HUQQA", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 133, Name = "NUSRET", NormalizedName = "NUSRET", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 134, Name = "GÜNAYDIN", NormalizedName = "GUNAYDIN", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 218, Name = "BURGER HOUSE", NormalizedName = "BURGER HOUSE", Category = ExpenseCategory.Restoran },
        new ExpenseLocationModel { Id = 243, Name = "OPET", NormalizedName = "OPET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 244, Name = "SHELL", NormalizedName = "SHELL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 245, Name = "BP", NormalizedName = "BP", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 246, Name = "PETROL OFİSİ", NormalizedName = "PETROL OFISI", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 247, Name = "TOTAL", NormalizedName = "TOTAL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 248, Name = "TOTALENERGIES", NormalizedName = "TOTALENERGIES", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 249, Name = "TP PETROL", NormalizedName = "TP PETROL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 250, Name = "AYGAZ", NormalizedName = "AYGAZ", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 251, Name = "MOGAZ", NormalizedName = "MOGAZ", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 252, Name = "LUKOIL", NormalizedName = "LUKOIL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 253, Name = "ALPET", NormalizedName = "ALPET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 254, Name = "KADOIL", NormalizedName = "KADOIL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 255, Name = "SUNPET", NormalizedName = "SUNPET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 256, Name = "GO PETROL", NormalizedName = "GO PETROL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 262, Name = "ZES", NormalizedName = "ZES", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 263, Name = "VOLTRUN", NormalizedName = "VOLTRUN", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 264, Name = "TRUGO", NormalizedName = "TRUGO", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 265, Name = "EŞARJ", NormalizedName = "ESARJ", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 266, Name = "SHARZ", NormalizedName = "SHARZ", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 267, Name = "ASTOR SARJ", NormalizedName = "ASTOR SARJ", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 268, Name = "BEEFULL", NormalizedName = "BEEFULL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 269, Name = "İETT", NormalizedName = "IETT", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 270, Name = "İSTANBULKART", NormalizedName = "ISTANBULKART", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 271, Name = "BELBİM", NormalizedName = "BELBIM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 272, Name = "METRO İSTANBUL", NormalizedName = "METRO ISTANBUL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 273, Name = "İZMİRKART", NormalizedName = "IZMIRKART", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 274, Name = "ANKARAKART", NormalizedName = "ANKARAKART", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 275, Name = "BURSAKART", NormalizedName = "BURSAKART", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 276, Name = "ANTALYAKART", NormalizedName = "ANTALYAKART", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 277, Name = "KENTKART", NormalizedName = "KENTKART", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 278, Name = "TCDD", NormalizedName = "TCDD", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 279, Name = "MARMARAY", NormalizedName = "MARMARAY", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 280, Name = "BAŞKENTRAY", NormalizedName = "BASKENTRAY", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 281, Name = "İZBAN", NormalizedName = "IZBAN", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 282, Name = "İDO", NormalizedName = "IDO", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 283, Name = "BUDO", NormalizedName = "BUDO", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 284, Name = "ŞEHİR HATLARI", NormalizedName = "SEHIR HATLARI", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 285, Name = "TURYOL", NormalizedName = "TURYOL", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 286, Name = "DENTUR", NormalizedName = "DENTUR", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 291, Name = "BİTAKSİ", NormalizedName = "BITAKSI", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 292, Name = "UBER", NormalizedName = "UBER", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 293, Name = "MARTI TAG", NormalizedName = "MARTI TAG", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 294, Name = "MARTI", NormalizedName = "MARTI", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 295, Name = "BİNBİN", NormalizedName = "BINBIN", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 296, Name = "HOP SCOOTER", NormalizedName = "HOP SCOOTER", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 297, Name = "TİKTAK", NormalizedName = "TIKTAK", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 298, Name = "MOOV", NormalizedName = "MOOV", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 299, Name = "GETİR ARAÇ", NormalizedName = "GETIR ARAC", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 300, Name = "ZIPCAR", NormalizedName = "ZIPCAR", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 301, Name = "AVIS", NormalizedName = "AVIS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 302, Name = "BUDGET", NormalizedName = "BUDGET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 303, Name = "ENTERPRISE", NormalizedName = "ENTERPRISE", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 304, Name = "SIXT", NormalizedName = "SIXT", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 305, Name = "GRENT", NormalizedName = "GRENT", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 306, Name = "HERTZ", NormalizedName = "HERTZ", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 307, Name = "EUROPCAR", NormalizedName = "EUROPCAR", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 312, Name = "HGS", NormalizedName = "HGS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 313, Name = "OGS", NormalizedName = "OGS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 314, Name = "KGM", NormalizedName = "KGM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 315, Name = "ICA", NormalizedName = "ICA", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 316, Name = "KUZEY MARMARA", NormalizedName = "KUZEY MARMARA", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 317, Name = "AVRASYA TÜNELİ", NormalizedName = "AVRASYA TUNELI", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 320, Name = "İSPARK", NormalizedName = "ISPARK", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 324, Name = "THY", NormalizedName = "THY", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 325, Name = "TÜRK HAVA YOLLARI", NormalizedName = "TURK HAVA YOLLARI", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 326, Name = "PEGASUS", NormalizedName = "PEGASUS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 327, Name = "FLYPGS", NormalizedName = "FLYPGS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 328, Name = "AJET", NormalizedName = "AJET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 329, Name = "ANADOLUJET", NormalizedName = "ANADOLUJET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 330, Name = "SUNEXPRESS", NormalizedName = "SUNEXPRESS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 331, Name = "ENUYGUN", NormalizedName = "ENUYGUN", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 332, Name = "OBİLET", NormalizedName = "OBILET", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 333, Name = "BILET.COM", NormalizedName = "BILET.COM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 334, Name = "METRO TURIZM", NormalizedName = "METRO TURIZM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 335, Name = "KAMİL KOÇ", NormalizedName = "KAMIL KOC", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 336, Name = "KÂMİL KOÇ", NormalizedName = "KÂMIL KOC", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 337, Name = "PAMUKKALE TURIZM", NormalizedName = "PAMUKKALE TURIZM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 338, Name = "VARAN", NormalizedName = "VARAN", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 339, Name = "NİLÜFER TURİZM", NormalizedName = "NILUFER TURIZM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 340, Name = "ALİ OSMAN ULUSOY", NormalizedName = "ALI OSMAN ULUSOY", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 341, Name = "SÜHA TURİZM", NormalizedName = "SUHA TURIZM", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 345, Name = "HAVAŞ", NormalizedName = "HAVAS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 346, Name = "HAVABÜS", NormalizedName = "HAVABUS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 386, Name = "KGM GECIS", NormalizedName = "KGM GECIS", Category = ExpenseCategory.Ulasim },
        new ExpenseLocationModel { Id = 393, Name = "ZARA", NormalizedName = "ZARA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 394, Name = "TRENDYOL MILLA", NormalizedName = "TRENDYOL MILLA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 395, Name = "H&M", NormalizedName = "H&M", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 396, Name = "MASSIMO DUTTI", NormalizedName = "MASSIMO DUTTI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 397, Name = "BERSHKA", NormalizedName = "BERSHKA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 398, Name = "PULL&BEAR", NormalizedName = "PULL&BEAR", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 399, Name = "PULL AND BEAR", NormalizedName = "PULL AND BEAR", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 400, Name = "STRADIVARIUS", NormalizedName = "STRADIVARIUS", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 401, Name = "OYSHO", NormalizedName = "OYSHO", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 402, Name = "MANGO", NormalizedName = "MANGO", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 403, Name = "LC WAIKIKI", NormalizedName = "LC WAIKIKI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 404, Name = "LCW", NormalizedName = "LCW", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 405, Name = "KOTON", NormalizedName = "KOTON", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 406, Name = "DEFACTO", NormalizedName = "DEFACTO", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 407, Name = "MAVİ", NormalizedName = "MAVI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 408, Name = "BOYNER", NormalizedName = "BOYNER", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 409, Name = "BEYMEN", NormalizedName = "BEYMEN", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 410, Name = "BEYMEN CLUB", NormalizedName = "BEYMEN CLUB", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 411, Name = "VAKKO", NormalizedName = "VAKKO", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 412, Name = "VAKKORAMA", NormalizedName = "VAKKORAMA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 413, Name = "İPEKYOL", NormalizedName = "IPEKYOL", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 414, Name = "TWIST", NormalizedName = "TWIST", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 415, Name = "MACHKA", NormalizedName = "MACHKA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 416, Name = "NETWORK", NormalizedName = "NETWORK", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 417, Name = "FABRIKA", NormalizedName = "FABRIKA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 418, Name = "YARGICI", NormalizedName = "YARGICI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 419, Name = "SARAR", NormalizedName = "SARAR", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 420, Name = "KIP", NormalizedName = "KIP", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 421, Name = "DAMAT", NormalizedName = "DAMAT", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 422, Name = "TWEEN", NormalizedName = "TWEEN", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 423, Name = "D'S DAMAT", NormalizedName = "D'S DAMAT", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 424, Name = "ALTINYILDIZ", NormalizedName = "ALTINYILDIZ", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 425, Name = "COLIN'S", NormalizedName = "COLIN'S", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 426, Name = "LOFT", NormalizedName = "LOFT", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 427, Name = "LTB", NormalizedName = "LTB", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 428, Name = "MUDO", NormalizedName = "MUDO", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 429, Name = "MUDO CITY", NormalizedName = "MUDO CITY", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 430, Name = "NAUTICA", NormalizedName = "NAUTICA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 431, Name = "GANT", NormalizedName = "GANT", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 432, Name = "LACOSTE", NormalizedName = "LACOSTE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 433, Name = "TOMMY HILFIGER", NormalizedName = "TOMMY HILFIGER", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 434, Name = "CALVIN KLEIN", NormalizedName = "CALVIN KLEIN", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 435, Name = "LEVI'S", NormalizedName = "LEVI'S", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 436, Name = "DIESEL", NormalizedName = "DIESEL", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 437, Name = "GUESS", NormalizedName = "GUESS", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 438, Name = "GAP", NormalizedName = "GAP", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 439, Name = "SUPERDRY", NormalizedName = "SUPERDRY", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 440, Name = "PENTİ", NormalizedName = "PENTI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 441, Name = "SUWEN", NormalizedName = "SUWEN", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 442, Name = "CALZEDONIA", NormalizedName = "CALZEDONIA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 443, Name = "INTIMISSIMI", NormalizedName = "INTIMISSIMI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 444, Name = "VICTORIA SECRET", NormalizedName = "VICTORIA SECRET", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 445, Name = "VICTORIA'S SECRET", NormalizedName = "VICTORIA'S SECRET", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 446, Name = "DAĞI", NormalizedName = "DAGI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 447, Name = "KOM", NormalizedName = "KOM", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 448, Name = "ADIDAS", NormalizedName = "ADIDAS", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 449, Name = "NIKE", NormalizedName = "NIKE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 450, Name = "PUMA", NormalizedName = "PUMA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 451, Name = "SKECHERS", NormalizedName = "SKECHERS", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 452, Name = "UNDER ARMOUR", NormalizedName = "UNDER ARMOUR", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 453, Name = "DECATHLON", NormalizedName = "DECATHLON", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 454, Name = "NEW BALANCE", NormalizedName = "NEW BALANCE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 455, Name = "REEBOK", NormalizedName = "REEBOK", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 456, Name = "ASICS", NormalizedName = "ASICS", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 457, Name = "VANS", NormalizedName = "VANS", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 458, Name = "CONVERSE", NormalizedName = "CONVERSE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 459, Name = "THE NORTH FACE", NormalizedName = "THE NORTH FACE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 460, Name = "COLUMBIA", NormalizedName = "COLUMBIA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 461, Name = "SALOMON", NormalizedName = "SALOMON", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 462, Name = "TIMBERLAND", NormalizedName = "TIMBERLAND", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 463, Name = "HUMMEL", NormalizedName = "HUMMEL", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 464, Name = "KAPPA", NormalizedName = "KAPPA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 465, Name = "LESCON", NormalizedName = "LESCON", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 466, Name = "SPORTIVE", NormalizedName = "SPORTIVE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 467, Name = "SNEAKS UP", NormalizedName = "SNEAKS UP", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 468, Name = "SUPERSTEP", NormalizedName = "SUPERSTEP", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 469, Name = "IN STREET", NormalizedName = "IN STREET", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 470, Name = "INTERSPORT", NormalizedName = "INTERSPORT", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 471, Name = "FLO", NormalizedName = "FLO", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 472, Name = "DEICHMANN", NormalizedName = "DEICHMANN", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 473, Name = "AYKOP", NormalizedName = "AYKOP", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 474, Name = "ELLE SHOES", NormalizedName = "ELLE SHOES", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 475, Name = "KEMAL TANCA", NormalizedName = "KEMAL TANCA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 476, Name = "DERIMOD", NormalizedName = "DERIMOD", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 477, Name = "DESA", NormalizedName = "DESA", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 478, Name = "TERGAN", NormalizedName = "TERGAN", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 479, Name = "GREYDER", NormalizedName = "GREYDER", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 480, Name = "SAMSONITE", NormalizedName = "SAMSONITE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 481, Name = "DİVARESE", NormalizedName = "DIVARESE", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 482, Name = "HOTİÇ", NormalizedName = "HOTIC", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 483, Name = "İNCİ", NormalizedName = "INCI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 498, Name = "AYAKKABI DÜNYASI", NormalizedName = "AYAKKABI DUNYASI", Category = ExpenseCategory.Giyim },
        new ExpenseLocationModel { Id = 534, Name = "NETFLIX", NormalizedName = "NETFLIX", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 535, Name = "SPOTIFY", NormalizedName = "SPOTIFY", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 536, Name = "YOUTUBE", NormalizedName = "YOUTUBE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 537, Name = "APPLE.COM", NormalizedName = "APPLE.COM", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 538, Name = "ITUNES", NormalizedName = "ITUNES", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 539, Name = "APP STORE", NormalizedName = "APP STORE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 540, Name = "GOOGLE PLAY", NormalizedName = "GOOGLE PLAY", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 541, Name = "GOOGLE STORAGE", NormalizedName = "GOOGLE STORAGE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 542, Name = "GOOGLE SERVICES", NormalizedName = "GOOGLE SERVICES", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 543, Name = "DISNEY", NormalizedName = "DISNEY", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 544, Name = "AMAZON PRIME", NormalizedName = "AMAZON PRIME", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 545, Name = "PRIME VIDEO", NormalizedName = "PRIME VIDEO", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 546, Name = "EXXEN", NormalizedName = "EXXEN", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 547, Name = "GAIN", NormalizedName = "GAIN", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 548, Name = "BLUTV", NormalizedName = "BLUTV", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 549, Name = "BEIN CONNECT", NormalizedName = "BEIN CONNECT", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 550, Name = "TOD TV", NormalizedName = "TOD TV", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 551, Name = "S SPORT", NormalizedName = "S SPORT", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 552, Name = "MUBI", NormalizedName = "MUBI", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 553, Name = "DEEZER", NormalizedName = "DEEZER", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 554, Name = "TIDAL", NormalizedName = "TIDAL", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 555, Name = "STORYTEL", NormalizedName = "STORYTEL", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 556, Name = "AUDIBLE", NormalizedName = "AUDIBLE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 557, Name = "STEAM", NormalizedName = "STEAM", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 558, Name = "VALVE", NormalizedName = "VALVE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 559, Name = "PLAYSTATION", NormalizedName = "PLAYSTATION", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 560, Name = "PSN", NormalizedName = "PSN", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 561, Name = "SONY INTERACTIVE", NormalizedName = "SONY INTERACTIVE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 562, Name = "XBOX", NormalizedName = "XBOX", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 563, Name = "MICROSOFT STORE", NormalizedName = "MICROSOFT STORE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 564, Name = "NINTENDO", NormalizedName = "NINTENDO", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 565, Name = "EPIC GAMES", NormalizedName = "EPIC GAMES", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 566, Name = "RIOT GAMES", NormalizedName = "RIOT GAMES", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 567, Name = "EA GAMES", NormalizedName = "EA GAMES", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 568, Name = "UBISOFT", NormalizedName = "UBISOFT", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 569, Name = "BLIZZARD", NormalizedName = "BLIZZARD", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 570, Name = "BATTLE.NET", NormalizedName = "BATTLE.NET", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 571, Name = "ROBLOX", NormalizedName = "ROBLOX", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 572, Name = "TWITCH", NormalizedName = "TWITCH", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 573, Name = "DISCORD", NormalizedName = "DISCORD", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 574, Name = "PATREON", NormalizedName = "PATREON", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 575, Name = "BİLETİX", NormalizedName = "BILETIX", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 576, Name = "PASSO", NormalizedName = "PASSO", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 577, Name = "BİLETİNİAL", NormalizedName = "BILETINIAL", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 578, Name = "BUBİLET", NormalizedName = "BUBILET", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 579, Name = "PARIBU CINEVERSE", NormalizedName = "PARIBU CINEVERSE", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 580, Name = "CINEMAXIMUM", NormalizedName = "CINEMAXIMUM", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 581, Name = "CINEMAPINK", NormalizedName = "CINEMAPINK", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 582, Name = "PRESTIGE CINEMA", NormalizedName = "PRESTIGE CINEMA", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 591, Name = "VIAPORT MARINA", NormalizedName = "VIAPORT MARINA", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 592, Name = "VIALAND", NormalizedName = "VIALAND", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 593, Name = "THE LAND OF LEGENDS", NormalizedName = "THE LAND OF LEGENDS", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 600, Name = "D&R", NormalizedName = "D&R", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 601, Name = "DNR", NormalizedName = "DNR", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 602, Name = "İDEFİX", NormalizedName = "IDEFIX", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 603, Name = "KİTAPYURDU", NormalizedName = "KITAPYURDU", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 604, Name = "BKM KİTAP", NormalizedName = "BKM KITAP", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 605, Name = "REMZİ KİTABEVİ", NormalizedName = "REMZI KITABEVI", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 606, Name = "PENGUEN KITABEVI", NormalizedName = "PENGUEN KITABEVI", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 610, Name = "TOYZZ SHOP", NormalizedName = "TOYZZ SHOP", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 611, Name = "ARMAĞAN OYUNCAK", NormalizedName = "ARMAGAN OYUNCAK", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 612, Name = "LEGO", NormalizedName = "LEGO", Category = ExpenseCategory.Eglence },
        new ExpenseLocationModel { Id = 664, Name = "ACIBADEM", NormalizedName = "ACIBADEM", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 665, Name = "MEMORIAL", NormalizedName = "MEMORIAL", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 666, Name = "MEDICAL PARK", NormalizedName = "MEDICAL PARK", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 667, Name = "MEDIPOL", NormalizedName = "MEDIPOL", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 668, Name = "FLORENCE NIGHTINGALE", NormalizedName = "FLORENCE NIGHTINGALE", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 669, Name = "LIV HOSPITAL", NormalizedName = "LIV HOSPITAL", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 670, Name = "GÜVEN HASTANESİ", NormalizedName = "GUVEN HASTANESI", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 671, Name = "ANADOLU SAĞLIK", NormalizedName = "ANADOLU SAGLIK", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 682, Name = "ATASUN", NormalizedName = "ATASUN", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 686, Name = "DÜNYAGÖZ", NormalizedName = "DUNYAGOZ", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 687, Name = "KUDRET GÖZ", NormalizedName = "KUDRET GOZ", Category = ExpenseCategory.Saglik },
        new ExpenseLocationModel { Id = 728, Name = "TURKCELL", NormalizedName = "TURKCELL", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 729, Name = "VODAFONE", NormalizedName = "VODAFONE", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 730, Name = "TÜRK TELEKOM", NormalizedName = "TURK TELEKOM", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 731, Name = "TTNET", NormalizedName = "TTNET", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 732, Name = "TÜRKNET", NormalizedName = "TURKNET", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 733, Name = "SÜPERONLİNE", NormalizedName = "SUPERONLINE", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 734, Name = "MILLENICOM", NormalizedName = "MILLENICOM", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 735, Name = "NETSMART", NormalizedName = "NETSMART", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 736, Name = "GIBIRNET", NormalizedName = "GIBIRNET", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 737, Name = "COKNET", NormalizedName = "COKNET", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 738, Name = "D-SMART", NormalizedName = "D SMART", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 739, Name = "DİGİTURK", NormalizedName = "DIGITURK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 740, Name = "TİVİBU", NormalizedName = "TIVIBU", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 741, Name = "KABLONET", NormalizedName = "KABLONET", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 742, Name = "TÜRKSAT", NormalizedName = "TURKSAT", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 745, Name = "ENERJİSA", NormalizedName = "ENERJISA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 746, Name = "BEDAŞ", NormalizedName = "BEDAS", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 747, Name = "AYEDAŞ", NormalizedName = "AYEDAS", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 748, Name = "CK BOĞAZİÇİ", NormalizedName = "CK BOGAZICI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 749, Name = "GEDİZ ELEKTRİK", NormalizedName = "GEDIZ ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 750, Name = "TOROSLAR ELEKTRIK", NormalizedName = "TOROSLAR ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 751, Name = "BAŞKENT ELEKTRİK", NormalizedName = "BASKENT ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 752, Name = "ULUDAĞ ELEKTRİK", NormalizedName = "ULUDAG ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 753, Name = "AYDEM", NormalizedName = "AYDEM", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 754, Name = "ÇORUH ELEKTRİK", NormalizedName = "CORUH ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 755, Name = "ARAS ELEKTRİK", NormalizedName = "ARAS ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 756, Name = "FIRAT ELEKTRIK", NormalizedName = "FIRAT ELEKTRIK", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 759, Name = "İGDAŞ", NormalizedName = "IGDAS", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 760, Name = "BAŞKENTGAZ", NormalizedName = "BASKENTGAZ", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 761, Name = "İZMİRGAZ", NormalizedName = "IZMIRGAZ", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 762, Name = "BURSAGAZ", NormalizedName = "BURSAGAZ", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 763, Name = "ENERYA", NormalizedName = "ENERYA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 764, Name = "AKSA DOĞALGAZ", NormalizedName = "AKSA DOGALGAZ", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 765, Name = "PALMET", NormalizedName = "PALMET", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 768, Name = "İSKİ", NormalizedName = "ISKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 769, Name = "ASKİ", NormalizedName = "ASKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 770, Name = "İZSU", NormalizedName = "IZSU", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 771, Name = "BUSKİ", NormalizedName = "BUSKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 772, Name = "DESKİ", NormalizedName = "DESKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 773, Name = "MASKİ", NormalizedName = "MASKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 774, Name = "GASKİ", NormalizedName = "GASKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 775, Name = "KOSKİ", NormalizedName = "KOSKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 776, Name = "TESKİ", NormalizedName = "TESKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 777, Name = "MESKİ", NormalizedName = "MESKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 778, Name = "SASKİ", NormalizedName = "SASKI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 779, Name = "DSİ", NormalizedName = "DSI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 782, Name = "ALLIANZ", NormalizedName = "ALLIANZ", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 783, Name = "AKSİGORTA", NormalizedName = "AKSIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 784, Name = "ANADOLU SIGORTA", NormalizedName = "ANADOLU SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 785, Name = "AXA SIGORTA", NormalizedName = "AXA SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 786, Name = "SOMPO", NormalizedName = "SOMPO", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 787, Name = "MAPFRE", NormalizedName = "MAPFRE", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 788, Name = "TÜRKİYE SİGORTA", NormalizedName = "TURKIYE SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 789, Name = "HDI SIGORTA", NormalizedName = "HDI SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 790, Name = "GROUPAMA", NormalizedName = "GROUPAMA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 791, Name = "GENERALI", NormalizedName = "GENERALI", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 792, Name = "NEVA SIGORTA", NormalizedName = "NEVA SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 793, Name = "DOĞA SİGORTA", NormalizedName = "DOGA SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 794, Name = "EUREKO SIGORTA", NormalizedName = "EUREKO SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 795, Name = "ZURICH SIGORTA", NormalizedName = "ZURICH SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 796, Name = "QUİCK SİGORTA", NormalizedName = "QUICK SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 797, Name = "KORU SIGORTA", NormalizedName = "KORU SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 798, Name = "UNICO SIGORTA", NormalizedName = "UNICO SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 799, Name = "HEPİYİ SİGORTA", NormalizedName = "HEPIYI SIGORTA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 802, Name = "AVIVASA", NormalizedName = "AVIVASA", Category = ExpenseCategory.Fatura },
        new ExpenseLocationModel { Id = 803, Name = "AGESA", NormalizedName = "AGESA", Category = ExpenseCategory.Fatura },
    };
}
