services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: finstance-api
    ports:
      - "5257:5257"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  ui:
    build:
      context: ./ui/finstance
      dockerfile: Dockerfile
    container_name: finstance-ui
    ports:
      - "3000:3000"
    environment:
      FINSTANCE_API_URL: http://api:5257
      NEXT_PUBLIC_DEFAULT_MONTH: ""
    depends_on:
      - api

volumes:
  finstance_data:
